### ISSUE TITLE
Soft Key Not Pop up

### ISSUE THREAD

**Issue by muralitheprogrammer** [syncfusion-content/maui-docs#1693]
I have a doubt in .NET MAUI. I am creating a point-of-sale (POS) application in .NET MAUI for a Windows platform. I am using an entry field and a search bar in my application, and it needs to be in full-screen mode. I have converted the program into an executable (exe) file and ran it on a POS machine (Essae Machine). However, when I touch the entry field, the soft keyboard does not pop up. Interestingly, the soft keyboard works in Google Chrome and AnyDesk on the same POS machine. Can you help me understand why the soft keyboard is not popping up in my application?

**Comment by muralitheprogrammer** [comment]
@JeanMarcFlamand

**Comment by PaulAndersonS** [comment]
Hi @muralitheprogrammer ,

Are you facing any issue related to Syncfusion controls? If your issue is specific to framework entry or general please post your doubts in the below section.

https://github.com/dotnet/maui/discussions

Also you can log the issue you faced to the dotnet maui team. https://github.com/dotnet/maui/issues
